# Generated by Django 4.2.6 on 2024-02-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokenTime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentime',
            name='timelimit',
            field=models.CharField(max_length=256),
        ),
    ]
