# Generated by Django 4.2.6 on 2023-11-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        ('TokenTime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_name', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=64)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='request.request')),
                ('tokenTime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TokenTime.tokentime')),
            ],
        ),
    ]
