# Generated by Django 4.2.6 on 2023-11-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
