# Generated by Django 4.2.6 on 2024-02-19 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_alter_tokens_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
