# Generated by Django 4.2.6 on 2024-02-29 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_alter_tokens_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
